### ISSUE TITLE
Ability to update service instance config properties

### ISSUE THREAD

**Issue by aegershman** [dawu415/CF-CLI-Create-Service-Push-Plugin#4]
When I make changes in my service-manifest.yml, I'd like the cf create-service-push to update any changes I've made to services within the manifest.

For example, if I create a config server with this manifest:
```
- name: config-server
  broker: p-config-server
  plan: standard
  parameters: '
  {
    "git": {
      "uri": "FOO"
    }
  '
```

and then I change the manifest to:
```
- name: config-server
  broker: p-config-server
  plan: standard
  parameters: '
  {
    "git": {
      "uri": "BAR"
    }
  '
```

the cf-cli-create-service-push-plugin will say `config-server already exists.` However, I'd like it to update my config-server instance with the new config

**Comment by dawu415** [comment]
I can see there's a couple of ways to manage this. There is also the issue of updating plans as well.

1) Just always update the parameters & plan.  It is assumed that the service-manifest is always in revision control (hopefully without credentials).

2) Similar to 1) but add an optional parameter [alwaysUpdateServiceInstance: true/false] 

3) We can compare the current plan with the new plan & the parameters. The new CF API has a way to list a service instance's parameters. However, this feature seems to be experimental and I don't want to introduce it until it is stable and accepted to be part of the CF API.

I'm thinking 2) might be a good compromise for now.

**Comment by dawu415** [comment]
Thanks. This has been introduced into v1.2.0.
