### ISSUE TITLE
Feature: Support services-manifest-variables.yml

### ISSUE THREAD

**Issue by TheFonz2017** [dawu415/CF-CLI-Create-Service-Push-Plugin#6]
Hi there!
Great job on creating this plugin! 
I would suggest a feature which is quite useful on the standard CF CLI push /  `manifest.yml`.
CF supports the outsourcing of variables used inside of `manifest.yml` to an external file.
See https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#variable-substitution.

This can be really helpful, if you need to have users append a unique prefix to service or application names (in order to avoid clashes when deployed inside the same CF space). 

It would be great if you could use the same pattern (`((variable_name_from_file))`) and simply add another CLI option like `--vars-file` where developers can specify the variables file to resolve placeholders against. One could then use the same vars-file (and hence variable values) that is used for the the standard `manifest.yml`. 

Cheers!

**Comment by dawu415** [comment]
Thanks for the suggestion, this has been put through in release v1.3.0. Please have a try and let me know how it goes.

**Comment by TheFonz2017** [comment]
Works like a charm! Thanks a lot for implementing this. 
That was really fast, too. So a big THANK YOU!
