### ISSUE TITLE
Feature: Channel through CF push command line args

### ISSUE THREAD

**Issue by TheFonz2017** [dawu415/CF-CLI-Create-Service-Push-Plugin#7]
Hi there,
I am using your plugin in my project and _before_ I used your plugin, I used 'cf push' with special flags (in my case 'cf push --vars-file manifest-variables.yml').
Since your plugin takes over the `cf push` (ideally) after all services have been created, how would one pass command line flags and args to the subsequent `cf push`?
Maybe you could channel all the flags your plugin does not know through to `cf push` automatically?

Cheers!

**Comment by dawu415** [comment]
Hi, it should be doing that already.  Run `cf csp  <existing CF push args>`
. Did you notice something that isn't going through for you?

**Comment by bpandola** [comment]
The CF CLI plugin architecture does not currently work with newer CLI features like --vars-file. (More verbose explanation [here](https://github.com/cloudfoundry/cli/issues/1399#issuecomment-409061226).

It would be possible to call `cf push` directly and pass through any arguments, but not sure of the risks of going outside the plugin architecture.

**Comment by dawu415** [comment]
v1.3.0 has been released with a `--push-as-subprocess`.   This will do cf push as a sub-process, if specified and will support the newer features of CF CLI.  The old cf push will still work.  This flag makes an assumption that cf/cf.exe is in the current working directory or it is in the system PATH.

**Comment by TheFonz2017** [comment]
Thank you very much! I was not aware of the fact that the cf push options are already channelled through. I will give it a shot for sure.
