### ISSUE TITLE
Consider changin this plugin to "just" create services

### ISSUE THREAD

**Issue by TheFonz2017** [dawu415/CF-CLI-Create-Service-Push-Plugin#8]
This plugin is a great idea as it tries to solve the feature unsupported by the CF CLI of creating several services at once, and describing them in a manifest.yml.

However, this plugin is also "duplicating" the functionality of pushing applications.
Maybe it would be a cleaner design (and easier to implement) if this plugin simply focussed on creating services. Requirements for that would be:

- provide a cf create-service**s** command plugin for the CF CLI
- read service descriptions from a manifest.yml (e.g. service-manifest.yml)
- allow variable resolution in service-manifest.yml using a standard CF variables file (see below)
- allow service configuration via inline JSON (usually passed to cf create-service via -c option) 

This would make the plugin more self-contained, and developers that need to create services and push their application(s) afterwards, can then simply call:
```
cf create-services (automatically reads service-manifest.yml) 
```
or
```
cf create-services -f my-service-manifest.yml
```
or 
```
cf create-services -f service-manifest.yml --vars-file manifest-variables.yml
```

A standard CF variables files (manifest-variables) looks as follows:
```
---
unique-prefix: aValue
app-prefix: anotherValue
subaccount-domain: domain
```

Inside a manifest.yml these would be referenced as:

```
...
services:
  - ((unique-prefix))-((app-prefix))-logging-service-instance
...

```

**Comment by dawu415** [comment]
You can already set the plugin to create services only, via adding the flag, --no-push.  This will create services only and not do a push.  

Doing some tests at the moment with variable substitution, so that shouldn't be far off.

**Comment by dawu415** [comment]
v1.3.0 is out, closing this now.
