### ISSUE TITLE
Plugin broken for services that take longer than 15 minutes to create

### ISSUE THREAD

**Issue by bpandola** [dawu415/CF-CLI-Create-Service-Push-Plugin#9]
Looks like a regression was introduced in v1.3.0 when a hardcoded timeout was added in place of what was once an indefinite loop ([here)](https://github.com/dawu415/CF-CLI-Create-Service-Push-Plugin/blob/master/serviceCreator/serviceCreator.go#L245).  We have services that take longer than 15 minutes to create and we are unable to use the latest version of the plugin (which contains other nice features, like variable substitution).

I will again make my case against a hardcoded timeout:  it's not possible to pick a value that will satisfy all current/future use cases.  Well-behaved brokers *will* appropriately update the service instance status and the loop will eventually be broken.  Additionally, the platform itself *already has* a [service creation timeout](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#polling-interval-and-duration) that, once exceeded, will also break the loop.

Please consider changing this back to an indefinite loop.  Thank you!

**Comment by dawu415** [comment]
Thanks for the suggestion. 
I've reverted it back to an indefinite loop.

https://github.com/dawu415/CF-CLI-Create-Service-Push-Plugin/releases/tag/1.3.1

Please have a try and let me know if it still causes issues elsewhere.  
Closing this for now.

**Comment by bpandola** [comment]
Many thanks for the quick turnaround on this!
